
uint8  Start_Flag
uint8  Length
uint8  Sequence
uint8  System_ID
uint8  Component
uint8  Message_ID

uint32 utcTime
int32  latitude
int32  longitude
int32  altPres
int32  altGNSS
uint32 accHoriz
uint16 accVert
uint16 accVel
int16  velVert
int16  nsVog
int16  ewVog
uint16 state
uint16 squawk
uint8  fixType
uint8  numSats
uint8  emStatus
uint8  control

uint8  CKA
uint8  CKB
uint8  CRC_PASS

Header header
