
uint8   Start_Flag
uint8   Length
uint8   Sequence
uint8   System_ID
uint8   Component
uint8   Message_ID

uint32  ICAO_address
int32   lat
int32   lon
int32   altitude
uint16  heading
uint16  hor_velocity
int16   ver_velocity
uint16  validFlags
uint16  squawk
uint8   altitude_type
char[9] callsign
uint8   emitter_type
uint8   tslc

uint8   CKA
uint8   CKB
uint8   CRC_PASS

Header header
