# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widget.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1850, 1000)
        self.map_change = QPushButton(Widget)
        self.map_change.setObjectName(u"map_change")
        self.map_change.setGeometry(QRect(1320, 60, 131, 41))
        self.frame_ownship = QFrame(Widget)
        self.frame_ownship.setObjectName(u"frame_ownship")
        self.frame_ownship.setGeometry(QRect(1180, 110, 651, 121))
        self.frame_ownship.setFrameShape(QFrame.StyledPanel)
        self.frame_ownship.setFrameShadow(QFrame.Raised)
        self.IN_Ownship_Alt = QLabel(self.frame_ownship)
        self.IN_Ownship_Alt.setObjectName(u"IN_Ownship_Alt")
        self.IN_Ownship_Alt.setGeometry(QRect(470, 30, 107, 17))
        self.IN_Ownship_Head = QLabel(self.frame_ownship)
        self.IN_Ownship_Head.setObjectName(u"IN_Ownship_Head")
        self.IN_Ownship_Head.setGeometry(QRect(470, 50, 107, 17))
        self.label_6 = QLabel(self.frame_ownship)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 50, 111, 17))
        self.label_7 = QLabel(self.frame_ownship)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(340, 30, 107, 17))
        self.label_8 = QLabel(self.frame_ownship)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(340, 70, 111, 17))
        self.label_9 = QLabel(self.frame_ownship)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 90, 111, 17))
        self.IN_Ownship_Hor_vel = QLabel(self.frame_ownship)
        self.IN_Ownship_Hor_vel.setObjectName(u"IN_Ownship_Hor_vel")
        self.IN_Ownship_Hor_vel.setGeometry(QRect(470, 70, 121, 17))
        self.IN_Ownship_Ver_vel = QLabel(self.frame_ownship)
        self.IN_Ownship_Ver_vel.setObjectName(u"IN_Ownship_Ver_vel")
        self.IN_Ownship_Ver_vel.setGeometry(QRect(470, 90, 121, 17))
        self.label_10 = QLabel(self.frame_ownship)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(19, 88, 107, 17))
        self.label_11 = QLabel(self.frame_ownship)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 50, 107, 17))
        self.IN_Ownship_y = QLabel(self.frame_ownship)
        self.IN_Ownship_y.setObjectName(u"IN_Ownship_y")
        self.IN_Ownship_y.setGeometry(QRect(149, 88, 107, 17))
        self.IN_Ownship_lat = QLabel(self.frame_ownship)
        self.IN_Ownship_lat.setObjectName(u"IN_Ownship_lat")
        self.IN_Ownship_lat.setGeometry(QRect(150, 30, 107, 17))
        self.label_13 = QLabel(self.frame_ownship)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 30, 107, 17))
        self.IN_Ownship_lon = QLabel(self.frame_ownship)
        self.IN_Ownship_lon.setObjectName(u"IN_Ownship_lon")
        self.IN_Ownship_lon.setGeometry(QRect(150, 50, 107, 17))
        self.IN_Ownship_x = QLabel(self.frame_ownship)
        self.IN_Ownship_x.setObjectName(u"IN_Ownship_x")
        self.IN_Ownship_x.setGeometry(QRect(149, 68, 107, 17))
        self.label_14 = QLabel(self.frame_ownship)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(19, 68, 107, 17))
        self.label = QLabel(self.frame_ownship)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 30, 41, 17))
        self.label_2 = QLabel(self.frame_ownship)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(270, 50, 41, 17))
        self.label_3 = QLabel(self.frame_ownship)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 70, 41, 17))
        self.label_4 = QLabel(self.frame_ownship)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(270, 90, 41, 17))
        self.label_5 = QLabel(self.frame_ownship)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(600, 30, 41, 17))
        self.label_26 = QLabel(self.frame_ownship)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(600, 50, 41, 17))
        self.label_27 = QLabel(self.frame_ownship)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(600, 70, 41, 17))
        self.label_28 = QLabel(self.frame_ownship)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(600, 90, 41, 17))
        self.label_37 = QLabel(self.frame_ownship)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 10, 201, 17))
        self.label_37.setFrameShape(QFrame.NoFrame)
        self.OPV_mission_button = QPushButton(self.frame_ownship)
        self.OPV_mission_button.setObjectName(u"OPV_mission_button")
        self.OPV_mission_button.setGeometry(QRect(410, 10, 81, 20))
        self.OPV_done_button = QPushButton(self.frame_ownship)
        self.OPV_done_button.setObjectName(u"OPV_done_button")
        self.OPV_done_button.setGeometry(QRect(320, 11, 81, 20))
        self.OPV_stby_button = QPushButton(self.frame_ownship)
        self.OPV_stby_button.setObjectName(u"OPV_stby_button")
        self.OPV_stby_button.setGeometry(QRect(220, 10, 91, 21))
        self.OPV_Status = QLabel(self.frame_ownship)
        self.OPV_Status.setObjectName(u"OPV_Status")
        self.OPV_Status.setGeometry(QRect(540, 10, 101, 21))
        self.frame_intruder = QFrame(Widget)
        self.frame_intruder.setObjectName(u"frame_intruder")
        self.frame_intruder.setGeometry(QRect(1180, 240, 651, 121))
        self.frame_intruder.setFrameShape(QFrame.StyledPanel)
        self.frame_intruder.setFrameShadow(QFrame.Raised)
        self.USV1_alt = QLabel(self.frame_intruder)
        self.USV1_alt.setObjectName(u"USV1_alt")
        self.USV1_alt.setGeometry(QRect(470, 30, 107, 17))
        self.USV1_head = QLabel(self.frame_intruder)
        self.USV1_head.setObjectName(u"USV1_head")
        self.USV1_head.setGeometry(QRect(470, 50, 107, 17))
        self.label_16 = QLabel(self.frame_intruder)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(340, 50, 111, 17))
        self.label_17 = QLabel(self.frame_intruder)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(340, 30, 107, 17))
        self.label_18 = QLabel(self.frame_intruder)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(340, 70, 111, 17))
        self.label_19 = QLabel(self.frame_intruder)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(340, 90, 111, 17))
        self.IN_USV1_Hor_vel = QLabel(self.frame_intruder)
        self.IN_USV1_Hor_vel.setObjectName(u"IN_USV1_Hor_vel")
        self.IN_USV1_Hor_vel.setGeometry(QRect(470, 70, 121, 17))
        self.IN_USV1_Ver_vel = QLabel(self.frame_intruder)
        self.IN_USV1_Ver_vel.setObjectName(u"IN_USV1_Ver_vel")
        self.IN_USV1_Ver_vel.setGeometry(QRect(470, 90, 121, 17))
        self.label_20 = QLabel(self.frame_intruder)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(19, 88, 107, 17))
        self.label_21 = QLabel(self.frame_intruder)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 50, 107, 17))
        self.IN_USV1_y = QLabel(self.frame_intruder)
        self.IN_USV1_y.setObjectName(u"IN_USV1_y")
        self.IN_USV1_y.setGeometry(QRect(149, 88, 107, 17))
        self.USV1_lat = QLabel(self.frame_intruder)
        self.USV1_lat.setObjectName(u"USV1_lat")
        self.USV1_lat.setGeometry(QRect(150, 30, 107, 17))
        self.label_23 = QLabel(self.frame_intruder)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 30, 107, 17))
        self.USV1_lon = QLabel(self.frame_intruder)
        self.USV1_lon.setObjectName(u"USV1_lon")
        self.USV1_lon.setGeometry(QRect(150, 50, 107, 17))
        self.IN_USV1_x = QLabel(self.frame_intruder)
        self.IN_USV1_x.setObjectName(u"IN_USV1_x")
        self.IN_USV1_x.setGeometry(QRect(149, 68, 107, 17))
        self.label_24 = QLabel(self.frame_intruder)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(19, 68, 107, 17))
        self.label_29 = QLabel(self.frame_intruder)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(270, 30, 41, 17))
        self.label_30 = QLabel(self.frame_intruder)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 50, 41, 17))
        self.label_31 = QLabel(self.frame_intruder)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(270, 90, 41, 17))
        self.label_32 = QLabel(self.frame_intruder)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(600, 30, 41, 17))
        self.label_33 = QLabel(self.frame_intruder)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(600, 90, 41, 17))
        self.label_34 = QLabel(self.frame_intruder)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(600, 70, 41, 17))
        self.label_35 = QLabel(self.frame_intruder)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(600, 50, 41, 17))
        self.label_36 = QLabel(self.frame_intruder)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(270, 70, 41, 17))
        self.label_38 = QLabel(self.frame_intruder)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(20, 10, 201, 17))
        self.label_38.setFrameShape(QFrame.NoFrame)
        self.USV1_Status = QLabel(self.frame_intruder)
        self.USV1_Status.setObjectName(u"USV1_Status")
        self.USV1_Status.setGeometry(QRect(540, 10, 101, 21))
        self.USV1_mission_button = QPushButton(self.frame_intruder)
        self.USV1_mission_button.setObjectName(u"USV1_mission_button")
        self.USV1_mission_button.setGeometry(QRect(410, 10, 81, 20))
        self.USV1_done_button = QPushButton(self.frame_intruder)
        self.USV1_done_button.setObjectName(u"USV1_done_button")
        self.USV1_done_button.setGeometry(QRect(320, 11, 81, 20))
        self.USV1_stby_button = QPushButton(self.frame_intruder)
        self.USV1_stby_button.setObjectName(u"USV1_stby_button")
        self.USV1_stby_button.setGeometry(QRect(220, 10, 91, 21))
        self.map_change_Down = QPushButton(Widget)
        self.map_change_Down.setObjectName(u"map_change_Down")
        self.map_change_Down.setGeometry(QRect(1180, 60, 131, 41))
        self.layoutWidget = QWidget(Widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1520, 60, 311, 19))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_39 = QLabel(self.layoutWidget)
        self.label_39.setObjectName(u"label_39")

        self.horizontalLayout.addWidget(self.label_39)

        self.CurrentTime = QLabel(self.layoutWidget)
        self.CurrentTime.setObjectName(u"CurrentTime")
        self.CurrentTime.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.CurrentTime)

        self.IN_ROS_TIME = QLabel(Widget)
        self.IN_ROS_TIME.setObjectName(u"IN_ROS_TIME")
        self.IN_ROS_TIME.setGeometry(QRect(1630, 80, 201, 16))
        self.IN_ROS_TIME.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_41 = QLabel(Widget)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(1520, 80, 101, 17))
        self.MAP = QLabel(Widget)
        self.MAP.setObjectName(u"MAP")
        self.MAP.setGeometry(QRect(20, 60, 1141, 911))
        self.MAP.setFrameShape(QFrame.Box)
        self.label_44 = QLabel(Widget)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 10, 661, 31))
        font = QFont()
        font.setPointSize(20)
        self.label_44.setFont(font)
        self.label_44.setFrameShadow(QFrame.Plain)
        self.label_44.setLineWidth(5)
        self.frame_intruder_2 = QFrame(Widget)
        self.frame_intruder_2.setObjectName(u"frame_intruder_2")
        self.frame_intruder_2.setGeometry(QRect(1180, 500, 651, 121))
        self.frame_intruder_2.setFrameShape(QFrame.StyledPanel)
        self.frame_intruder_2.setFrameShadow(QFrame.Raised)
        self.UAV1_alt = QLabel(self.frame_intruder_2)
        self.UAV1_alt.setObjectName(u"UAV1_alt")
        self.UAV1_alt.setGeometry(QRect(470, 30, 107, 17))
        self.UAV1_head = QLabel(self.frame_intruder_2)
        self.UAV1_head.setObjectName(u"UAV1_head")
        self.UAV1_head.setGeometry(QRect(470, 50, 107, 17))
        self.label_83 = QLabel(self.frame_intruder_2)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(340, 50, 111, 17))
        self.label_84 = QLabel(self.frame_intruder_2)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(340, 30, 107, 17))
        self.label_85 = QLabel(self.frame_intruder_2)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(340, 70, 111, 17))
        self.label_86 = QLabel(self.frame_intruder_2)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(340, 90, 111, 17))
        self.IN_UAV1_Hor_vel = QLabel(self.frame_intruder_2)
        self.IN_UAV1_Hor_vel.setObjectName(u"IN_UAV1_Hor_vel")
        self.IN_UAV1_Hor_vel.setGeometry(QRect(470, 70, 121, 17))
        self.IN_UAV1_Ver_vel = QLabel(self.frame_intruder_2)
        self.IN_UAV1_Ver_vel.setObjectName(u"IN_UAV1_Ver_vel")
        self.IN_UAV1_Ver_vel.setGeometry(QRect(470, 90, 121, 17))
        self.label_87 = QLabel(self.frame_intruder_2)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(19, 88, 107, 17))
        self.label_88 = QLabel(self.frame_intruder_2)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(20, 50, 107, 17))
        self.IN_UAV1_y = QLabel(self.frame_intruder_2)
        self.IN_UAV1_y.setObjectName(u"IN_UAV1_y")
        self.IN_UAV1_y.setGeometry(QRect(149, 88, 107, 17))
        self.UAV1_lat = QLabel(self.frame_intruder_2)
        self.UAV1_lat.setObjectName(u"UAV1_lat")
        self.UAV1_lat.setGeometry(QRect(150, 30, 107, 17))
        self.label_90 = QLabel(self.frame_intruder_2)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(20, 30, 107, 17))
        self.UAV1_lon = QLabel(self.frame_intruder_2)
        self.UAV1_lon.setObjectName(u"UAV1_lon")
        self.UAV1_lon.setGeometry(QRect(150, 50, 107, 17))
        self.IN_UAV1_x = QLabel(self.frame_intruder_2)
        self.IN_UAV1_x.setObjectName(u"IN_UAV1_x")
        self.IN_UAV1_x.setGeometry(QRect(149, 68, 107, 17))
        self.label_91 = QLabel(self.frame_intruder_2)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(19, 68, 107, 17))
        self.label_93 = QLabel(self.frame_intruder_2)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(270, 30, 41, 17))
        self.label_94 = QLabel(self.frame_intruder_2)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(270, 50, 41, 17))
        self.label_95 = QLabel(self.frame_intruder_2)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(270, 90, 41, 17))
        self.label_96 = QLabel(self.frame_intruder_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(600, 30, 41, 17))
        self.label_97 = QLabel(self.frame_intruder_2)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(600, 90, 41, 17))
        self.label_98 = QLabel(self.frame_intruder_2)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(600, 70, 41, 17))
        self.label_99 = QLabel(self.frame_intruder_2)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(600, 50, 41, 17))
        self.label_100 = QLabel(self.frame_intruder_2)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(270, 70, 41, 17))
        self.label_101 = QLabel(self.frame_intruder_2)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(20, 10, 201, 17))
        self.label_101.setFrameShape(QFrame.NoFrame)
        self.UAV1_mission_button = QPushButton(self.frame_intruder_2)
        self.UAV1_mission_button.setObjectName(u"UAV1_mission_button")
        self.UAV1_mission_button.setGeometry(QRect(410, 10, 81, 20))
        self.UAV1_stby_button = QPushButton(self.frame_intruder_2)
        self.UAV1_stby_button.setObjectName(u"UAV1_stby_button")
        self.UAV1_stby_button.setGeometry(QRect(220, 10, 91, 21))
        self.UAV1_Status = QLabel(self.frame_intruder_2)
        self.UAV1_Status.setObjectName(u"UAV1_Status")
        self.UAV1_Status.setGeometry(QRect(540, 10, 101, 21))
        self.UAV1_done_button = QPushButton(self.frame_intruder_2)
        self.UAV1_done_button.setObjectName(u"UAV1_done_button")
        self.UAV1_done_button.setGeometry(QRect(320, 11, 81, 20))
        self.frame_intruder_3 = QFrame(Widget)
        self.frame_intruder_3.setObjectName(u"frame_intruder_3")
        self.frame_intruder_3.setGeometry(QRect(1180, 630, 651, 121))
        self.frame_intruder_3.setFrameShape(QFrame.StyledPanel)
        self.frame_intruder_3.setFrameShadow(QFrame.Raised)
        self.UAV2_alt = QLabel(self.frame_intruder_3)
        self.UAV2_alt.setObjectName(u"UAV2_alt")
        self.UAV2_alt.setGeometry(QRect(470, 30, 107, 17))
        self.UAV2_head = QLabel(self.frame_intruder_3)
        self.UAV2_head.setObjectName(u"UAV2_head")
        self.UAV2_head.setGeometry(QRect(470, 50, 107, 17))
        self.label_102 = QLabel(self.frame_intruder_3)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(340, 50, 111, 17))
        self.label_103 = QLabel(self.frame_intruder_3)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(340, 30, 107, 17))
        self.label_104 = QLabel(self.frame_intruder_3)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(340, 70, 111, 17))
        self.label_105 = QLabel(self.frame_intruder_3)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(340, 90, 111, 17))
        self.IN_UAV2_Hor_vel = QLabel(self.frame_intruder_3)
        self.IN_UAV2_Hor_vel.setObjectName(u"IN_UAV2_Hor_vel")
        self.IN_UAV2_Hor_vel.setGeometry(QRect(470, 70, 121, 17))
        self.IN_UAV2_Ver_vel = QLabel(self.frame_intruder_3)
        self.IN_UAV2_Ver_vel.setObjectName(u"IN_UAV2_Ver_vel")
        self.IN_UAV2_Ver_vel.setGeometry(QRect(470, 90, 121, 17))
        self.label_106 = QLabel(self.frame_intruder_3)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(20, 90, 107, 17))
        self.label_107 = QLabel(self.frame_intruder_3)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(20, 50, 107, 17))
        self.IN_UAV2_y = QLabel(self.frame_intruder_3)
        self.IN_UAV2_y.setObjectName(u"IN_UAV2_y")
        self.IN_UAV2_y.setGeometry(QRect(149, 90, 107, 17))
        self.UAV2_lat = QLabel(self.frame_intruder_3)
        self.UAV2_lat.setObjectName(u"UAV2_lat")
        self.UAV2_lat.setGeometry(QRect(150, 32, 107, 17))
        self.label_109 = QLabel(self.frame_intruder_3)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(20, 30, 107, 17))
        self.UAV2_lon = QLabel(self.frame_intruder_3)
        self.UAV2_lon.setObjectName(u"UAV2_lon")
        self.UAV2_lon.setGeometry(QRect(150, 52, 107, 17))
        self.IN_UAV2_x = QLabel(self.frame_intruder_3)
        self.IN_UAV2_x.setObjectName(u"IN_UAV2_x")
        self.IN_UAV2_x.setGeometry(QRect(149, 70, 107, 17))
        self.label_110 = QLabel(self.frame_intruder_3)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(20, 70, 107, 17))
        self.label_112 = QLabel(self.frame_intruder_3)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(270, 30, 41, 17))
        self.label_113 = QLabel(self.frame_intruder_3)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(270, 50, 41, 17))
        self.label_114 = QLabel(self.frame_intruder_3)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(270, 90, 41, 17))
        self.label_115 = QLabel(self.frame_intruder_3)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(600, 30, 41, 17))
        self.label_116 = QLabel(self.frame_intruder_3)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(600, 90, 41, 17))
        self.label_117 = QLabel(self.frame_intruder_3)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(600, 70, 41, 17))
        self.label_118 = QLabel(self.frame_intruder_3)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(600, 50, 41, 17))
        self.label_119 = QLabel(self.frame_intruder_3)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(270, 70, 41, 17))
        self.label_120 = QLabel(self.frame_intruder_3)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setGeometry(QRect(20, 10, 201, 17))
        self.label_120.setFrameShape(QFrame.NoFrame)
        self.UAV2_mission_button = QPushButton(self.frame_intruder_3)
        self.UAV2_mission_button.setObjectName(u"UAV2_mission_button")
        self.UAV2_mission_button.setGeometry(QRect(410, 9, 81, 20))
        self.UAV2_stby_button = QPushButton(self.frame_intruder_3)
        self.UAV2_stby_button.setObjectName(u"UAV2_stby_button")
        self.UAV2_stby_button.setGeometry(QRect(220, 9, 91, 21))
        self.UAV2_Status = QLabel(self.frame_intruder_3)
        self.UAV2_Status.setObjectName(u"UAV2_Status")
        self.UAV2_Status.setGeometry(QRect(540, 9, 101, 21))
        self.UAV2_done_button = QPushButton(self.frame_intruder_3)
        self.UAV2_done_button.setObjectName(u"UAV2_done_button")
        self.UAV2_done_button.setGeometry(QRect(320, 10, 81, 20))
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(1180, 760, 651, 211))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.OPV_pos_share = QPushButton(self.tab)
        self.OPV_pos_share.setObjectName(u"OPV_pos_share")
        self.OPV_pos_share.setGeometry(QRect(140, 10, 111, 21))
        self.label_45 = QLabel(self.tab)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(270, 16, 91, 17))
        self.label_46 = QLabel(self.tab)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(270, 36, 91, 17))
        self.OPV_share_lat = QLabel(self.tab)
        self.OPV_share_lat.setObjectName(u"OPV_share_lat")
        self.OPV_share_lat.setGeometry(QRect(370, 16, 131, 17))
        self.OPV_share_lon = QLabel(self.tab)
        self.OPV_share_lon.setObjectName(u"OPV_share_lon")
        self.OPV_share_lon.setGeometry(QRect(370, 36, 131, 17))
        self.OPV_acc_lon = QLabel(self.tab)
        self.OPV_acc_lon.setObjectName(u"OPV_acc_lon")
        self.OPV_acc_lon.setGeometry(QRect(330, 140, 160, 30))
        font1 = QFont()
        font1.setPointSize(15)
        self.OPV_acc_lon.setFont(font1)
        self.label_74 = QLabel(self.tab)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(180, 80, 280, 30))
        self.label_74.setFont(font1)
        self.OPV_acc_lat = QLabel(self.tab)
        self.OPV_acc_lat.setObjectName(u"OPV_acc_lat")
        self.OPV_acc_lat.setGeometry(QRect(330, 110, 160, 30))
        self.OPV_acc_lat.setFont(font1)
        self.label_76 = QLabel(self.tab)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(110, 110, 210, 30))
        self.label_76.setFont(font1)
        self.label_77 = QLabel(self.tab)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(110, 140, 210, 30))
        self.label_77.setFont(font1)
        self.OPV_shared_pos_clear = QPushButton(self.tab)
        self.OPV_shared_pos_clear.setObjectName(u"OPV_shared_pos_clear")
        self.OPV_shared_pos_clear.setGeometry(QRect(140, 40, 111, 21))
        self.OPV_acc_lat_2 = QLabel(self.tab)
        self.OPV_acc_lat_2.setObjectName(u"OPV_acc_lat_2")
        self.OPV_acc_lat_2.setGeometry(QRect(490, 110, 40, 30))
        self.OPV_acc_lat_2.setFont(font1)
        self.OPV_acc_lat_3 = QLabel(self.tab)
        self.OPV_acc_lat_3.setObjectName(u"OPV_acc_lat_3")
        self.OPV_acc_lat_3.setGeometry(QRect(490, 140, 40, 30))
        self.OPV_acc_lat_3.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.USV1_acc_lon = QLabel(self.tab_2)
        self.USV1_acc_lon.setObjectName(u"USV1_acc_lon")
        self.USV1_acc_lon.setGeometry(QRect(330, 120, 180, 30))
        self.USV1_acc_lon.setFont(font1)
        self.label_50 = QLabel(self.tab_2)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(110, 120, 210, 30))
        self.label_50.setFont(font1)
        self.USV1_acc_lat = QLabel(self.tab_2)
        self.USV1_acc_lat.setObjectName(u"USV1_acc_lat")
        self.USV1_acc_lat.setGeometry(QRect(330, 80, 170, 30))
        self.USV1_acc_lat.setFont(font1)
        self.label_52 = QLabel(self.tab_2)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(110, 80, 210, 30))
        self.label_52.setFont(font1)
        self.label_62 = QLabel(self.tab_2)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(190, 40, 280, 30))
        self.label_62.setFont(font1)
        self.OPV_acc_lat_4 = QLabel(self.tab_2)
        self.OPV_acc_lat_4.setObjectName(u"OPV_acc_lat_4")
        self.OPV_acc_lat_4.setGeometry(QRect(500, 80, 40, 30))
        self.OPV_acc_lat_4.setFont(font1)
        self.OPV_acc_lat_5 = QLabel(self.tab_2)
        self.OPV_acc_lat_5.setObjectName(u"OPV_acc_lat_5")
        self.OPV_acc_lat_5.setGeometry(QRect(500, 120, 40, 30))
        self.OPV_acc_lat_5.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_149 = QLabel(self.tab_9)
        self.label_149.setObjectName(u"label_149")
        self.label_149.setGeometry(QRect(110, 120, 210, 30))
        self.label_149.setFont(font1)
        self.USV2_acc_lat = QLabel(self.tab_9)
        self.USV2_acc_lat.setObjectName(u"USV2_acc_lat")
        self.USV2_acc_lat.setGeometry(QRect(330, 80, 170, 30))
        self.USV2_acc_lat.setFont(font1)
        self.label_151 = QLabel(self.tab_9)
        self.label_151.setObjectName(u"label_151")
        self.label_151.setGeometry(QRect(110, 80, 210, 30))
        self.label_151.setFont(font1)
        self.USV2_acc_lon = QLabel(self.tab_9)
        self.USV2_acc_lon.setObjectName(u"USV2_acc_lon")
        self.USV2_acc_lon.setGeometry(QRect(330, 120, 170, 30))
        self.USV2_acc_lon.setFont(font1)
        self.label_153 = QLabel(self.tab_9)
        self.label_153.setObjectName(u"label_153")
        self.label_153.setGeometry(QRect(190, 40, 280, 30))
        self.label_153.setFont(font1)
        self.OPV_acc_lat_6 = QLabel(self.tab_9)
        self.OPV_acc_lat_6.setObjectName(u"OPV_acc_lat_6")
        self.OPV_acc_lat_6.setGeometry(QRect(500, 120, 40, 30))
        self.OPV_acc_lat_6.setFont(font1)
        self.OPV_acc_lat_7 = QLabel(self.tab_9)
        self.OPV_acc_lat_7.setObjectName(u"OPV_acc_lat_7")
        self.OPV_acc_lat_7.setGeometry(QRect(500, 80, 40, 30))
        self.OPV_acc_lat_7.setFont(font1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_148 = QLabel(self.tab_3)
        self.label_148.setObjectName(u"label_148")
        self.label_148.setGeometry(QRect(190, 40, 280, 30))
        self.label_148.setFont(font1)
        self.UAV1_acc_lat = QLabel(self.tab_3)
        self.UAV1_acc_lat.setObjectName(u"UAV1_acc_lat")
        self.UAV1_acc_lat.setGeometry(QRect(330, 80, 170, 30))
        self.UAV1_acc_lat.setFont(font1)
        self.UAV1_acc_lon = QLabel(self.tab_3)
        self.UAV1_acc_lon.setObjectName(u"UAV1_acc_lon")
        self.UAV1_acc_lon.setGeometry(QRect(330, 120, 170, 30))
        self.UAV1_acc_lon.setFont(font1)
        self.label_144 = QLabel(self.tab_3)
        self.label_144.setObjectName(u"label_144")
        self.label_144.setGeometry(QRect(110, 120, 210, 30))
        self.label_144.setFont(font1)
        self.label_146 = QLabel(self.tab_3)
        self.label_146.setObjectName(u"label_146")
        self.label_146.setGeometry(QRect(110, 80, 210, 30))
        self.label_146.setFont(font1)
        self.OPV_acc_lat_8 = QLabel(self.tab_3)
        self.OPV_acc_lat_8.setObjectName(u"OPV_acc_lat_8")
        self.OPV_acc_lat_8.setGeometry(QRect(500, 120, 40, 30))
        self.OPV_acc_lat_8.setFont(font1)
        self.OPV_acc_lat_9 = QLabel(self.tab_3)
        self.OPV_acc_lat_9.setObjectName(u"OPV_acc_lat_9")
        self.OPV_acc_lat_9.setGeometry(QRect(500, 80, 40, 30))
        self.OPV_acc_lat_9.setFont(font1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.UAV2_acc_lat = QLabel(self.tab_4)
        self.UAV2_acc_lat.setObjectName(u"UAV2_acc_lat")
        self.UAV2_acc_lat.setGeometry(QRect(330, 80, 170, 30))
        self.UAV2_acc_lat.setFont(font1)
        self.UAV2_acc_lon = QLabel(self.tab_4)
        self.UAV2_acc_lon.setObjectName(u"UAV2_acc_lon")
        self.UAV2_acc_lon.setGeometry(QRect(330, 120, 170, 30))
        self.UAV2_acc_lon.setFont(font1)
        self.label_70 = QLabel(self.tab_4)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(110, 120, 210, 30))
        self.label_70.setFont(font1)
        self.label_71 = QLabel(self.tab_4)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(190, 40, 280, 30))
        self.label_71.setFont(font1)
        self.label_72 = QLabel(self.tab_4)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(110, 80, 210, 30))
        self.label_72.setFont(font1)
        self.OPV_acc_lat_10 = QLabel(self.tab_4)
        self.OPV_acc_lat_10.setObjectName(u"OPV_acc_lat_10")
        self.OPV_acc_lat_10.setGeometry(QRect(500, 120, 40, 30))
        self.OPV_acc_lat_10.setFont(font1)
        self.OPV_acc_lat_11 = QLabel(self.tab_4)
        self.OPV_acc_lat_11.setObjectName(u"OPV_acc_lat_11")
        self.OPV_acc_lat_11.setGeometry(QRect(500, 80, 40, 30))
        self.OPV_acc_lat_11.setFont(font1)
        self.tabWidget.addTab(self.tab_4, "")
        self.frame_intruder_4 = QFrame(Widget)
        self.frame_intruder_4.setObjectName(u"frame_intruder_4")
        self.frame_intruder_4.setGeometry(QRect(1180, 370, 651, 121))
        self.frame_intruder_4.setFrameShape(QFrame.StyledPanel)
        self.frame_intruder_4.setFrameShadow(QFrame.Raised)
        self.USV2_alt = QLabel(self.frame_intruder_4)
        self.USV2_alt.setObjectName(u"USV2_alt")
        self.USV2_alt.setGeometry(QRect(470, 30, 107, 17))
        self.USV2_head = QLabel(self.frame_intruder_4)
        self.USV2_head.setObjectName(u"USV2_head")
        self.USV2_head.setGeometry(QRect(470, 50, 107, 17))
        self.label_22 = QLabel(self.frame_intruder_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(340, 50, 111, 17))
        self.label_25 = QLabel(self.frame_intruder_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(340, 30, 107, 17))
        self.label_54 = QLabel(self.frame_intruder_4)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(340, 70, 111, 17))
        self.label_55 = QLabel(self.frame_intruder_4)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(340, 90, 111, 17))
        self.IN_USV2_Hor_vel = QLabel(self.frame_intruder_4)
        self.IN_USV2_Hor_vel.setObjectName(u"IN_USV2_Hor_vel")
        self.IN_USV2_Hor_vel.setGeometry(QRect(470, 70, 121, 17))
        self.IN_USV2_Ver_vel = QLabel(self.frame_intruder_4)
        self.IN_USV2_Ver_vel.setObjectName(u"IN_USV2_Ver_vel")
        self.IN_USV2_Ver_vel.setGeometry(QRect(470, 90, 121, 17))
        self.label_56 = QLabel(self.frame_intruder_4)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(19, 88, 107, 17))
        self.label_57 = QLabel(self.frame_intruder_4)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 50, 107, 17))
        self.IN_USV2_y = QLabel(self.frame_intruder_4)
        self.IN_USV2_y.setObjectName(u"IN_USV2_y")
        self.IN_USV2_y.setGeometry(QRect(149, 88, 107, 17))
        self.USV2_lat = QLabel(self.frame_intruder_4)
        self.USV2_lat.setObjectName(u"USV2_lat")
        self.USV2_lat.setGeometry(QRect(150, 30, 107, 17))
        self.label_58 = QLabel(self.frame_intruder_4)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 30, 107, 17))
        self.USV2_lon = QLabel(self.frame_intruder_4)
        self.USV2_lon.setObjectName(u"USV2_lon")
        self.USV2_lon.setGeometry(QRect(150, 50, 107, 17))
        self.IN_USV2_x = QLabel(self.frame_intruder_4)
        self.IN_USV2_x.setObjectName(u"IN_USV2_x")
        self.IN_USV2_x.setGeometry(QRect(149, 68, 107, 17))
        self.label_59 = QLabel(self.frame_intruder_4)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(19, 68, 107, 17))
        self.label_60 = QLabel(self.frame_intruder_4)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(270, 30, 41, 17))
        self.label_61 = QLabel(self.frame_intruder_4)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(270, 50, 41, 17))
        self.label_78 = QLabel(self.frame_intruder_4)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(270, 90, 41, 17))
        self.label_79 = QLabel(self.frame_intruder_4)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(600, 30, 41, 17))
        self.label_80 = QLabel(self.frame_intruder_4)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(600, 90, 41, 17))
        self.label_81 = QLabel(self.frame_intruder_4)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(600, 70, 41, 17))
        self.label_82 = QLabel(self.frame_intruder_4)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(600, 50, 41, 17))
        self.label_89 = QLabel(self.frame_intruder_4)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(270, 70, 41, 17))
        self.label_92 = QLabel(self.frame_intruder_4)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(20, 10, 201, 17))
        self.label_92.setFrameShape(QFrame.NoFrame)
        self.USV2_Status = QLabel(self.frame_intruder_4)
        self.USV2_Status.setObjectName(u"USV2_Status")
        self.USV2_Status.setGeometry(QRect(540, 10, 101, 21))
        self.USV2_mission_button = QPushButton(self.frame_intruder_4)
        self.USV2_mission_button.setObjectName(u"USV2_mission_button")
        self.USV2_mission_button.setGeometry(QRect(410, 10, 81, 20))
        self.USV2_done_button = QPushButton(self.frame_intruder_4)
        self.USV2_done_button.setObjectName(u"USV2_done_button")
        self.USV2_done_button.setGeometry(QRect(320, 11, 81, 20))
        self.USV2_stby_button = QPushButton(self.frame_intruder_4)
        self.USV2_stby_button.setObjectName(u"USV2_stby_button")
        self.USV2_stby_button.setGeometry(QRect(220, 10, 91, 21))
        self.layoutWidget.raise_()
        self.frame_ownship.raise_()
        self.map_change.raise_()
        self.frame_intruder.raise_()
        self.map_change_Down.raise_()
        self.IN_ROS_TIME.raise_()
        self.label_41.raise_()
        self.MAP.raise_()
        self.label_44.raise_()
        self.frame_intruder_2.raise_()
        self.frame_intruder_3.raise_()
        self.tabWidget.raise_()
        self.frame_intruder_4.raise_()

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.map_change.setText(QCoreApplication.translate("Widget", u"MAP ZOOM OUT", None))
        self.IN_Ownship_Alt.setText(QCoreApplication.translate("Widget", u"Ownship_Alt", None))
        self.IN_Ownship_Head.setText(QCoreApplication.translate("Widget", u"Ownship_Head", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_Ownship_Hor_vel.setText(QCoreApplication.translate("Widget", u"Ownship_Hor_vel", None))
        self.IN_Ownship_Ver_vel.setText(QCoreApplication.translate("Widget", u"Ownship_Ver_vel", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_Ownship_y.setText(QCoreApplication.translate("Widget", u"Ownship_y", None))
        self.IN_Ownship_lat.setText(QCoreApplication.translate("Widget", u"Ownship_lat", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.IN_Ownship_lon.setText(QCoreApplication.translate("Widget", u"Ownship_lon", None))
        self.IN_Ownship_x.setText(QCoreApplication.translate("Widget", u"Ownship_x", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.label.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_26.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_27.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_37.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">OPV INFORMATION</span></p></body></html>", None))
        self.OPV_mission_button.setText(QCoreApplication.translate("Widget", u"MISSION", None))
        self.OPV_done_button.setText(QCoreApplication.translate("Widget", u"DONE", None))
        self.OPV_stby_button.setText(QCoreApplication.translate("Widget", u"STBY", None))
        self.OPV_Status.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">STATUS</p></body></html>", None))
        self.USV1_alt.setText(QCoreApplication.translate("Widget", u"USV_Alt", None))
        self.USV1_head.setText(QCoreApplication.translate("Widget", u"USV_Head", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_USV1_Hor_vel.setText(QCoreApplication.translate("Widget", u"USV_Hor_vel", None))
        self.IN_USV1_Ver_vel.setText(QCoreApplication.translate("Widget", u"USV_Ver_vel", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_USV1_y.setText(QCoreApplication.translate("Widget", u"USV_y", None))
        self.USV1_lat.setText(QCoreApplication.translate("Widget", u"USV_lat", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.USV1_lon.setText(QCoreApplication.translate("Widget", u"USV_lon", None))
        self.IN_USV1_x.setText(QCoreApplication.translate("Widget", u"USV_x", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_30.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_31.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_32.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_33.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_34.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_35.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_36.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_38.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">USV_1 INFORMATION</span></p></body></html>", None))
        self.USV1_Status.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">STATUS</p></body></html>", None))
        self.USV1_mission_button.setText(QCoreApplication.translate("Widget", u"MISSION", None))
        self.USV1_done_button.setText(QCoreApplication.translate("Widget", u"DONE", None))
        self.USV1_stby_button.setText(QCoreApplication.translate("Widget", u"STBY", None))
        self.map_change_Down.setText(QCoreApplication.translate("Widget", u"MAP ZOOM IN", None))
        self.label_39.setText(QCoreApplication.translate("Widget", u"TIME                 :", None))
        self.CurrentTime.setText(QCoreApplication.translate("Widget", u"Current TIME", None))
        self.IN_ROS_TIME.setText(QCoreApplication.translate("Widget", u"ROS_TIME", None))
        self.label_41.setText(QCoreApplication.translate("Widget", u"ROS_TIME       :", None))
        self.MAP.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">M  A  P</span></p></body></html>", None))
        self.label_44.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p>Monitoring Program for Multi Uanmanned Vehicles</p></body></html>", None))
        self.UAV1_alt.setText(QCoreApplication.translate("Widget", u"UAV1_Alt", None))
        self.UAV1_head.setText(QCoreApplication.translate("Widget", u"UAV1_Head", None))
        self.label_83.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_84.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_85.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_86.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_UAV1_Hor_vel.setText(QCoreApplication.translate("Widget", u"UAV1_Hor_vel", None))
        self.IN_UAV1_Ver_vel.setText(QCoreApplication.translate("Widget", u"UAV1_Ver_vel", None))
        self.label_87.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_88.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_UAV1_y.setText(QCoreApplication.translate("Widget", u"UAV1_y", None))
        self.UAV1_lat.setText(QCoreApplication.translate("Widget", u"UAV1_lat", None))
        self.label_90.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.UAV1_lon.setText(QCoreApplication.translate("Widget", u"UAV1_lon", None))
        self.IN_UAV1_x.setText(QCoreApplication.translate("Widget", u"UAV1_x", None))
        self.label_91.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.label_93.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_94.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_95.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_96.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_97.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_98.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_99.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_100.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_101.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">DRONE_1 INFORMATION</span></p></body></html>", None))
        self.UAV1_mission_button.setText(QCoreApplication.translate("Widget", u"MISSION", None))
        self.UAV1_stby_button.setText(QCoreApplication.translate("Widget", u"STBY", None))
        self.UAV1_Status.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">STATUS</p></body></html>", None))
        self.UAV1_done_button.setText(QCoreApplication.translate("Widget", u"DONE", None))
        self.UAV2_alt.setText(QCoreApplication.translate("Widget", u"UAV2_Alt", None))
        self.UAV2_head.setText(QCoreApplication.translate("Widget", u"UAV2_Head", None))
        self.label_102.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_103.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_104.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_105.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_UAV2_Hor_vel.setText(QCoreApplication.translate("Widget", u"UAV2_Hor_vel", None))
        self.IN_UAV2_Ver_vel.setText(QCoreApplication.translate("Widget", u"UAV2_Ver_vel", None))
        self.label_106.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_107.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_UAV2_y.setText(QCoreApplication.translate("Widget", u"UAV2_y", None))
        self.UAV2_lat.setText(QCoreApplication.translate("Widget", u"UAV2_lat", None))
        self.label_109.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.UAV2_lon.setText(QCoreApplication.translate("Widget", u"UAV2_lon", None))
        self.IN_UAV2_x.setText(QCoreApplication.translate("Widget", u"UAV2_x", None))
        self.label_110.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.label_112.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_113.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_114.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_115.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_116.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_117.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_118.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_119.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_120.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">DRONE_2 INFORMATION</span></p></body></html>", None))
        self.UAV2_mission_button.setText(QCoreApplication.translate("Widget", u"MISSION", None))
        self.UAV2_stby_button.setText(QCoreApplication.translate("Widget", u"STBY", None))
        self.UAV2_Status.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">STATUS</p></body></html>", None))
        self.UAV2_done_button.setText(QCoreApplication.translate("Widget", u"DONE", None))
        self.OPV_pos_share.setText(QCoreApplication.translate("Widget", u"Position Share", None))
        self.label_45.setText(QCoreApplication.translate("Widget", u"Latitude       :", None))
        self.label_46.setText(QCoreApplication.translate("Widget", u"Logitude      :", None))
        self.OPV_share_lat.setText(QCoreApplication.translate("Widget", u"Latitude        [deg]", None))
        self.OPV_share_lon.setText(QCoreApplication.translate("Widget", u"Longitude     [deg]", None))
        self.OPV_acc_lon.setText(QCoreApplication.translate("Widget", u"diff_East", None))
        self.label_74.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Accident District</p></body></html>", None))
        self.OPV_acc_lat.setText(QCoreApplication.translate("Widget", u"diff_North", None))
        self.label_76.setText(QCoreApplication.translate("Widget", u"ECEF_North_distance :", None))
        self.label_77.setText(QCoreApplication.translate("Widget", u"   ECEF_East_distance :", None))
        self.OPV_shared_pos_clear.setText(QCoreApplication.translate("Widget", u"Clear", None))
        self.OPV_acc_lat_2.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.OPV_acc_lat_3.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Widget", u"OPV", None))
        self.USV1_acc_lon.setText(QCoreApplication.translate("Widget", u"diff_East", None))
        self.label_50.setText(QCoreApplication.translate("Widget", u"   ECEF_East_distance :", None))
        self.USV1_acc_lat.setText(QCoreApplication.translate("Widget", u"diff_North", None))
        self.label_52.setText(QCoreApplication.translate("Widget", u"ECEF_North_distance :", None))
        self.label_62.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Accident District</p></body></html>", None))
        self.OPV_acc_lat_4.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.OPV_acc_lat_5.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Widget", u"USV_1", None))
        self.label_149.setText(QCoreApplication.translate("Widget", u"   ECEF_East_distance :", None))
        self.USV2_acc_lat.setText(QCoreApplication.translate("Widget", u"diff_North", None))
        self.label_151.setText(QCoreApplication.translate("Widget", u"ECEF_North_distance :", None))
        self.USV2_acc_lon.setText(QCoreApplication.translate("Widget", u"diff_East", None))
        self.label_153.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Accident District</p></body></html>", None))
        self.OPV_acc_lat_6.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.OPV_acc_lat_7.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("Widget", u"USV_2", None))
        self.label_148.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Accident District</p></body></html>", None))
        self.UAV1_acc_lat.setText(QCoreApplication.translate("Widget", u"diff_North", None))
        self.UAV1_acc_lon.setText(QCoreApplication.translate("Widget", u"diff_East", None))
        self.label_144.setText(QCoreApplication.translate("Widget", u"   ECEF_East_distance :", None))
        self.label_146.setText(QCoreApplication.translate("Widget", u"ECEF_North_distance :", None))
        self.OPV_acc_lat_8.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.OPV_acc_lat_9.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Widget", u"DRONE1", None))
        self.UAV2_acc_lat.setText(QCoreApplication.translate("Widget", u"diff_North", None))
        self.UAV2_acc_lon.setText(QCoreApplication.translate("Widget", u"diff_East", None))
        self.label_70.setText(QCoreApplication.translate("Widget", u"   ECEF_East_distance :", None))
        self.label_71.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Accident District</p></body></html>", None))
        self.label_72.setText(QCoreApplication.translate("Widget", u"ECEF_North_distance :", None))
        self.OPV_acc_lat_10.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.OPV_acc_lat_11.setText(QCoreApplication.translate("Widget", u" [m]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Widget", u"DRONE2", None))
        self.USV2_alt.setText(QCoreApplication.translate("Widget", u"USV_Alt", None))
        self.USV2_head.setText(QCoreApplication.translate("Widget", u"USV_Head", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_54.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_55.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_USV2_Hor_vel.setText(QCoreApplication.translate("Widget", u"USV_Hor_vel", None))
        self.IN_USV2_Ver_vel.setText(QCoreApplication.translate("Widget", u"USV_Ver_vel", None))
        self.label_56.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_57.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_USV2_y.setText(QCoreApplication.translate("Widget", u"USV_y", None))
        self.USV2_lat.setText(QCoreApplication.translate("Widget", u"USV_lat", None))
        self.label_58.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.USV2_lon.setText(QCoreApplication.translate("Widget", u"USV_lon", None))
        self.IN_USV2_x.setText(QCoreApplication.translate("Widget", u"USV_x", None))
        self.label_59.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.label_60.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_61.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_78.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_79.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_80.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_81.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_82.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_89.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_92.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">USV_2 INFORMATION</span></p></body></html>", None))
        self.USV2_Status.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">STATUS</p></body></html>", None))
        self.USV2_mission_button.setText(QCoreApplication.translate("Widget", u"MISSION", None))
        self.USV2_done_button.setText(QCoreApplication.translate("Widget", u"DONE", None))
        self.USV2_stby_button.setText(QCoreApplication.translate("Widget", u"STBY", None))
    # retranslateUi

